postgres:
    image: postgres:12
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "twittergram"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql