postgre:
    image: postgres:12
    hostname: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "twittergram"
